version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13" 
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false

    post_install:
      - poetry install --with docs

