version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13" 
  jobs:
    post_create_environment:
      - "pip install mkdocs mkdocs-macros-plugin mkdocs-material "
      - "pip install mkdocstrings mkdocstrings-python pymdown-extensions"
      - "pip install mkdocs-exclude-search"
