version: 2

mkdocs:
  configuration: payment_emulation/mkdocs.yml

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13" 
  jobs:
    post_create_environment:
      # - pip install poetry
      # - poetry config virtualenvs.create false
      - "pip install mkdocs mkdocs-macros-plugin mkdocs-material "
      - "pip install mkdocs-static-i18n mkdocstrings mkdocstrings-python"
      - "pip install pymdown-extensions"
    post_install:
    #   - poetry install --no-interaction --no-ansi --only docs
      - cd ./payment_emulation
