site_name: Payment Emulation
repo_url: https://github.com/valdean7/payment_emulation
repo_name: valdean7/payment_emulation

theme:
    name: material
    language: pt-BR

    palette:
      - scheme: default
        primary: indigo
        toggle:
          icon: material/weather-night
          name: Modo noturno

      - scheme: slate
        primary: deep indigo
        toggle:
          icon: material/weather-sunny
          name: Modo claro

nav:
  - Inicio: index.md
  - CLI: CLI.md
  - Transações: transactions.md
  - Conta e Cartão: account_and_card.md
  - PaymentSDK: payment/PaymentSDK.md
  - Generators: utils/generators.md
  - Modal: payment_modal.md
  - Middleware: middleware.md
  - Contribuição: contributing.md

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - attr_list

plugins:
  - macros

  - search

  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            heading_level: 2

  - exclude-search:
      exclude:
        - assets/*

extra:
  vars:
    lib_name: "payment-emulation"
    lib_name_sc: "payment_emulation"
    installed_apps: "payment_emulation.payment"
    full_inport: "from payment_emulation.payment.paymentSDK import PaymentSDK"
