version: 2

mkdocs:
  configuration: payment_emulation/mkdocs.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.10" 
  jobs:
    post_create_environment:
      - pip install --upgrade pip
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --no-interaction --no-ansi --only docs
      - cd ./payment_emulation
