version: 2

mkdocs:
  configuration: payment_emulation/mkdocs.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.10" 
  jobs:
    pre_install:
      - pip install poetry
      - poetry install --no-interaction --no-ansi --only docs
