version: 2

mkdocs:
  configuration: payment_emulation/mkdocs.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.10" 
  jobs:
    pre_install:
      - python -m venv .venv
      - source .venv/bin/activate
      - pip install poetry
      - poetry install --no-interaction --no-ansi --only docs

    post_install:
      - poetry install --only docs 

