version: 2

mkdocs:
  configuration: payment_emulation/mkdocs.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.10" 
  jobs:
    pre_install:
      - export PATH="$READTHEDOCS_VIRTUALENV_PATH/bin:$PATH"
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --no-interaction --no-ansi --only docs
      - cd ./payment_emulation
