name: Test pipiline
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'
      - name: Install poetry
        run: pip install poetry

      - name: Install project dependencies for test
        run: poetry install --without docs

      - name: Run tests
        run: cd ./payment_emulation && poetry run pytest --cov-report=xml
